:PROPERTIES:
:ID:       1e63ac4b-895b-4d99-982c-e7573f143d88
:END:
#+title: Consciousness

* consciousness according to [[id:c25546d3-5dc7-40e2-bb0b-62c9bfa08c9c][Cognitive Sciences]]
In cognitive sciences, we may refer to consciousness in several ways, for
example:
+ By being sentient
+ By being awake (not asleep or incapacitated in any matter)
+ access consciousness: a thought that broadcast widely on a subject's brain; it
  drives its behaviour.
+ phenomenal consciousness or *qualia*: subjective feelings; elicited feelings
  from stimuli.
** What makes us conscious and why? The hard problem of Consciousness
To answer these questions is either difficult or easy, depending on under which
light we are solving the puzzle.

With *Phenomenology* we reflect on our conscious lige from a subjective point of
view; /what is like/ to taste/do/smell something. We clearly can retrieve the
conscious feeling that comes with a given activity.

On the other hand, we have no way so far of determining how our physical brain
gives place to consciousness, i.e., we don't know how consciousness emerges from
pure brain activity. /There is a gap between phenomenology and neuroscience/.

How our first person consciousness emerges from our the third person brain
activity? In science we usually analyze phenomena in a third person perspective,
such as the properties of a fluid in motion; the same happens with neuroscience
and the brain, we see this activity as a third person phenomena, while we
experience consciousness as first person. The hard problem exists because there
is a gap between these two models.

*** Frank Jackson's argument
Frank Jackson belives that we won't be able to solve the hard problem. He
proposed a thought experiment.

Imagine a neuroscientist that lives in a white and black room, then, she hasn't
seen any color throughout her life. She knows everything about color theory and
about how the brain processes light to form vision.

One day, she goes outside this room, so she can see color for the first time, at
this moment, she learns something new about human vision, she learns the
subjective feeling of "seeing". This kind of feeling cannot be learned, nor
predicted from information coming from books.
* [[id:0bbfb8af-197e-4f70-a7e4-6df5cdb277d7][Philosophy]]
Descartes postulated that our conscious knowledge was more reliable than any
natural science.


* Related
+ [[id:c25546d3-5dc7-40e2-bb0b-62c9bfa08c9c][Cognitive Sciences]]
+ [[id:0bbfb8af-197e-4f70-a7e4-6df5cdb277d7][Philosophy]]
